### PR TITLE
Add member - bhoot

### PR DESCRIPTION
**Pull request by bhootd**

### CODE REVIEW

**Comment by xvw** [comment]
Thanks a lot for your contribution! 
I'll merge when the CI is green!
I hope that you will find an interest to the webring!
- Do not forget to add the webring link on your website: https://github.com/muhokama/ring?tab=readme-ov-file#linking-the-webring-on-your-website
- And there is also a federated blog that you can freely join: https://github.com/muhokama/ring?tab=readme-ov-file#participation-in-the-federated-blog

**Comment by bhootd** [comment]
Thank you. Yes those steps are on my to-do list, soon after I get added to the ring.

**Comment by bhootd** [comment]
> Do not forget to add the webring link on your website

Done, [universally](https://bhoot.dev) in the footer, and specifically [here](https://bhoot.dev/about/#part-of-small-web).

**Comment by xvw** [comment]
Thank you very much! 
There is a small typo (its `muhokama` and not `Mohukama`) but it seems perfect. Thanks a lot! 
Happy to see a new blog (written in OCaml) on the ring!

**Comment by bhootd** [comment]
Fixed the typos too!

**Pull request merged**
